### ISSUE TITLE
FinalScene.mp4 not fully uploaded

### ISSUE THREAD

**Issue by MsVader** [PacktPublishing/Unreal-Engine-5-Character-Creation-Animation-and-Cinematics#3]
Unreal-Engine-5-Character-Creation-Animation-and-Cinematics-main\FullFinalUE5Project

FinalScene.mp4 is only 1 KB. It does not play.

**Comment by packt-simrana** [comment]
Hi MsVader,

I think you have mistakenly used the wrong path to the file. If you look carefully, the path you're using contains a backslash instead of a forward slash. I tried downloading and using the file and it's playing well without any issue. If you use the correct path, you'll see that the size of the file is 98.7 MB.

The actual path is: Unreal-Engine-5-Character-Creation-Animation-and-Cinematics/FullFinalUE5Project/FinalScene.mp4

You can also download using this link: https://github.com/PacktPublishing/Unreal-Engine-5-Character-Creation-Animation-and-Cinematics/blob/main/FullFinalUE5Project/FinalScene.mp4

I'm sure the solutions provided above will work for you and you'll be able to play the file without any error.

Feel free to reach out if you face any doubt, I will be happy to help :)
