### ISSUE TITLE
Chapter 5 issues with lines not lining up correctly on model.

### ISSUE THREAD

**Issue by froismo** [PacktPublishing/Unreal-Engine-5-Character-Creation-Animation-and-Cinematics#6]
<img width="962" alt="Screenshot 2023-02-12 154344" src="https://user-images.githubusercontent.com/1802249/218344663-4f463dd8-a962-420b-951f-4de48ed6ec83.png">

I don't think this github repo is really followed, but I'm not sure where to look for answers.  Looks like models and maps uploaded to github  don't line up correctly.

**Comment by Henk3D** [comment]
Hi Russel,

Thanks for reading my Book. 

Please download the new Model file here:
https://github.com/PacktPublishing/Unreal-Engine-5-Character-Creation-Animation-and-Cinematics/blob/main/Chapter05/RobotDrone.fbx

I have a fixed a small issue that was causing an Orientation error in Quixel Mixer.

Re-Import the Model. Apply the maps like shown in Chapter 5. The cause of your issue is that you need to select "Placement" in the menu and choose "Box Projection" and select "Tiling" as the method for orienting the Drone_Lines.png map.

I am attaching screenshots for you.

Have a great day! ;)
![2023-02-28_152906](https://user-images.githubusercontent.com/34553596/221886226-da60d48a-8cab-4479-8b9b-e2b50f51c41a.jpg)



![2023-02-28_153352](https://user-images.githubusercontent.com/34553596/221886325-75a9aec0-97d9-4624-815c-7dc863f98aa0.jpg)
